# Generated by Django 5.2.6 on 2025-10-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="nausea",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
